sudo: required

language: perl
perl:
  - "5.20"    

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init 
  - perl -V

install:
  - cpanm MooseX::FollowPBP URI::Escape URL::Encode Config::YAML File::Basename Bio::MAGETAB Date::Parse Test::MockObject Text::TabularDisplay Log::Dispatch::File Archive::Extract

before_script:
    - export PATH=$PWD/tests:$PATH
    - export PERL5LIB=$PWD/perl_modules:$PERL5LIB

script:
  - bash run-tests.sh
