sudo: required

language: perl
perl:
  - "5.26"    

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init 
  - perl -V
  - if test -e $HOME/miniconda/bin; then
        echo "miniconda already installed.";
    else
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
      
      rm -rf $HOME/miniconda;  
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda update -q conda;
  
      conda info -a;

      conda config --add channels defaults;
      conda config --add channels conda-forge;
      conda config --add channels bioconda;
      conda config --add channels ebi-gene-expression-group;

      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION perl perl-atlas-modules;
    fi  

install:
  - export PATH="$HOME/miniconda/bin:$PATH";
  - source activate test-environment
  - conda install --yes -c bioconda perl-archive-extract
  - cpanm IO::CaptureOutput DBD::Oracle

before_script:
    - export PATH=$PWD/tests:$PATH
    - export PERL5LIB=$PWD/perl_modules:$PERL5LIB

cache:
  directories:
    - $HOME/miniconda

script:
  - bash run-tests.sh

before_cache:
    - if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
    - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
